[package]
name = "layoutparser-ort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hf-hub = "0.3.2"
image = "0.25.1"
ndarray = "0.15.6"
ort = "2.0.0-rc.2"
thiserror = "1.0.59"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }
